version: "3.3"

services:
  logstash:
    image: $IMAGE_NAME
    environment:
      xpack.monitoring.enabled: "false"
    volumes:
      - type: bind
        source: /vagrant
        target: /vagrant
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1GB
      restart_policy:
        condition: any
        max_attempts: 20
        window: 30s
      placement:
        constraints:
          - node.labels.id==$WORKER
          - node.role==worker
